version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
    reviewers:
      - "xBlaz3kx"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
    reviewers:
      - "xBlaz3kx"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
    reviewers:
      - "xBlaz3kx"