version: '3.7'
services:
  chargepi-website:
    build:
      context: .
      target: website
    volumes:
      - ./build/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chargepi-http.rule=Host(`chargepi.cc`)"
      - "traefik.http.routers.chargepi-http.entrypoints=web"
      - "traefik.http.routers.chargepi-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.chargepi-https.rule=Host(`chargepi.cc`)"
      - "traefik.http.routers.chargepi-https.tls=true"
      - "traefik.http.routers.chargepi-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.chargepi-https.entrypoints=web-secure"
      - "traefik.http.services.chargepi-https.loadbalancer.server.port=80"
      - "traefik.docker.network=server"
networks:
  default:
    external:
      name: server