name: Lint
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Lint
        run: |
          pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Typecheck
        run: |
          pnpm tsc
