name: 'Test'
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master
    paths-ignore:
      - "**/*.md"

  workflow_dispatch:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Generate coverage report
        uses: artiomtr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          github-token: ${{ secrets.GITHUB_TOKEN }}