name: 'Test'
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master
    paths-ignore:
      - "**/*.md"

  workflow_dispatch:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Run tests
        run: source .env && pnpm jest --reporters="summary" --reporters="github-actions"
